## @File        : application-*.yml
## @Author      : 정재백
## @Since       : 2024-07-28
## @Description : 환경설정파일
## @Site        : https://devlog.ntiple.com
debug: false
server:
  port: 8080
  forward-headers-strategy: "FRAMEWORK"
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

spring:
  jackson:
    ## 로컬에서는 디버깅을 위해 모든 속성을 조회한다
    default-property-inclusion: "always"
  datasource-main:
    driver-class-name: "org.h2.Driver"
    ##  메모리 전용 DB 사용시 아래 설정 사용
    jdbc-url: "jdbc:h2:mem:main"
    # jdbc-url: jdbc:h2:./demo-app.db
    username: "sa"
    password: 
  datasource-dss:
    hikari:
      connection-test-query: "SELECT 1"
      pool-name: "dbp-dss"
      auto-commit: false
    driver-class-name: "org.h2.Driver"
    jdbc-url: "jdbc:h2:mem:session"
    username: "sa"
    password: 
    # driver-class-name: "org.postgresql.Driver"
    # jdbc-url: "jdbc:postgresql://192.168.0.2:5432/legacy_java_was"
    # username: "legacy_java_was"
    # password: ""

logging:
  level:
    root: "INFO"

system:
  profile: "local"
  assets:
    cache:
      dir: "${java.io.tmpdir}/legacy-java-was/log"
    js:
      minify: false
    scss:
      minify: false
  dbsession-query:
    ## [ JDBC세션 질의문 (H2 / LOCAL)
    create-session-table:
      # - "DROP TABLE SPRING_SESSION_ATTRIBUTES"
      # - "DROP TABLE SPRING_SESSION"
      - "\
        CREATE TABLE SPRING_SESSION ( \
          PRIMARY_ID CHAR(36) NOT NULL, \
          SESSION_ID CHAR(36) NOT NULL, \
          CREATION_TIME BIGINT NOT NULL, \
          LAST_ACCESS_TIME BIGINT NOT NULL, \
          MAX_INACTIVE_INTERVAL INT NOT NULL, \
          EXPIRY_TIME BIGINT NOT NULL, \
          PRINCIPAL_NAME VARCHAR(100), \
          LOGIN_ID VARCHAR(36), \
          CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID) \
        )"
      - "CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID)"
      - "CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME)"
      - "CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME)"
      - "\
        CREATE TABLE SPRING_SESSION_ATTRIBUTES ( \
          SESSION_PRIMARY_ID CHAR(36) NOT NULL, \
          ATTRIBUTE_NAME VARCHAR(200) NOT NULL, \
          ATTRIBUTE_BYTES LONGVARCHAR NOT NULL, \
          CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME), \
          CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE \
        )"
    create-session: "\
      INSERT INTO \
        SPRING_SESSION \
        (PRIMARY_ID, SESSION_ID, CREATION_TIME, LAST_ACCESS_TIME, MAX_INACTIVE_INTERVAL, EXPIRY_TIME, PRINCIPAL_NAME) \
      VALUES \
        (?, ?, ?, ?, ?, ?, ?) \
      "
    create-session-attribute: "\
      INSERT INTO \
        SPRING_SESSION_ATTRIBUTES \
        (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) \
      VALUES \
        (?, ?, ?)\
      "
    get-session: "\
      SELECT \
        S.PRIMARY_ID, \
        S.SESSION_ID, \
        S.CREATION_TIME, \
        S.LAST_ACCESS_TIME, \
        S.MAX_INACTIVE_INTERVAL, \
        SA.ATTRIBUTE_NAME, \
        SA.ATTRIBUTE_BYTES \
      FROM \
        SPRING_SESSION S \
        LEFT JOIN SPRING_SESSION_ATTRIBUTES SA \
      ON \
        S.PRIMARY_ID = SA.SESSION_PRIMARY_ID \
      WHERE \
        S.SESSION_ID = ? \
      "
    update-session: "\
      UPDATE \
        SPRING_SESSION \
        SET \
          SESSION_ID = ?, LAST_ACCESS_TIME = ?, MAX_INACTIVE_INTERVAL = ?, EXPIRY_TIME = ?, PRINCIPAL_NAME = ? \
      WHERE \
        PRIMARY_ID = ?\
      "
    update-session-attribute: "\
      UPDATE \
        SPRING_SESSION_ATTRIBUTES \
        SET \
          ATTRIBUTE_BYTES = ? \
      WHERE \
        SESSION_PRIMARY_ID = ? AND \
        ATTRIBUTE_NAME = ?\
      "
    delete-session: "\
      DELETE FROM \
        SPRING_SESSION \
      WHERE \
        SESSION_ID = ? AND \
        MAX_INACTIVE_INTERVAL >= 0\
      "
    delete-session-attribute: "\
      DELETE FROM \
        SPRING_SESSION_ATTRIBUTES \
      WHERE \
        SESSION_PRIMARY_ID = ? AND \
        ATTRIBUTE_NAME = ?\
      "
    list-sessions-by-principal-name: "\
      SELECT \
        S.PRIMARY_ID, \
        S.SESSION_ID, \
        S.CREATION_TIME, \
        S.LAST_ACCESS_TIME, \
        S.MAX_INACTIVE_INTERVAL, \
        SA.ATTRIBUTE_NAME, \
        SA.ATTRIBUTE_BYTES \
      FROM \
        SPRING_SESSION S \
        LEFT OUTER JOIN SPRING_SESSION_ATTRIBUTES SA \
      ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID \
      WHERE \
        S.PRINCIPAL_NAME = ?\
      "
    delete-sessions-by-expiry-time: "\
      DELETE \
      FROM \
        SPRING_SESSION \
      WHERE \
        EXPIRY_TIME < ? \
      "
    update-login-id: "\
      UPDATE \
        SPRING_SESSION \
        SET LOGIN_ID = ? \
      WHERE \
        SESSION_ID = ?\
      "
    find-login-id: "\
      SELECT \
        PRIMARY_ID \
      FROM \
        SPRING_SESSION \
      WHERE \
        LOGIN_ID = ? AND \
        SESSION_ID != ?\
      "
    delete-session-attribute-all: "\
      DELETE FROM \
        SPRING_SESSION_ATTRIBUTES \
      WHERE \
        SESSION_PRIMARY_ID = ?\
      "
    delete-session-by-id: "\
      DELETE FROM \
        SPRING_SESSION \
      WHERE \
        PRIMARY_ID = ?\
      "
    ## ] JDBC세션 질의문 (H2 / LOCAL)