## @File        : application
## @Author      : 정재백
## @Since       : 2024-07-28
## @Description : 환경설정파일
## @Site        : https://devlog.ntiple.com
debug: false
spring:
  application:
    name: "demo"
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  servlet:
    multipart:
      maxFileSize: "1GB"
      maxRequestSize: "1GB"
  datasource-main:
    driverClassName: "org.h2.Driver"
    ##  메모리 전용 DB 사용시 아래 설정 사용
    jdbcUrl: "jdbc:h2:mem:main"
    # jdbcUrl: jdbc:h2:./demo-app.db
    username: "sa"
    password: 
  datasource-dss:
    driverClassName: "org.h2.Driver"
    jdbcUrl: "jdbc:h2:mem:session"
    username: "sa"
    password: 
    dbsession-query:
      create-session: "INSERT INTO SPRING_SESSION (PRIMARY_ID, SESSION_ID, CREATION_TIME, LAST_ACCESS_TIME, MAX_INACTIVE_INTERVAL, EXPIRY_TIME, PRINCIPAL_NAME) VALUES (?, ?, ?, ?, ?, ?, ?)"
      create-session-attribute: "INSERT INTO SPRING_SESSION_ATTRIBUTES(SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) VALUES (?, ?, ?)"
      get-session: "SELECT S.PRIMARY_ID, S.SESSION_ID, S.CREATION_TIME, S.LAST_ACCESS_TIME, S.MAX_INACTIVE_INTERVAL, SA.ATTRIBUTE_NAME, SA.ATTRIBUTE_BYTES FROM SPRING_SESSION S LEFT JOIN SPRING_SESSION_ATTRIBUTES SA ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID WHERE S.SESSION_ID = ?"
      update-session: "UPDATE SPRING_SESSION SET SESSION_ID = ?, LAST_ACCESS_TIME = ?, MAX_INACTIVE_INTERVAL = ?, EXPIRY_TIME = ?, PRINCIPAL_NAME = ? WHERE PRIMARY_ID = ?"
      update-session-attribute: "UPDATE SPRING_SESSION_ATTRIBUTES SET ATTRIBUTE_BYTES = ? WHERE SESSION_PRIMARY_ID = ? AND ATTRIBUTE_NAME = ?"
      delete-session: "DELETE FROM SPRING_SESSION WHERE SESSION_ID = ? AND MAX_INACTIVE_INTERVAL >= 0"
      delete-session-attribute: "DELETE FROM SPRING_SESSION_ATTRIBUTES WHERE SESSION_PRIMARY_ID = ? AND ATTRIBUTE_NAME = ?"
      list-sessions-by-principal-name: "SELECT S.PRIMARY_ID, S.SESSION_ID, S.CREATION_TIME, S.LAST_ACCESS_TIME, S.MAX_INACTIVE_INTERVAL, SA.ATTRIBUTE_NAME, SA.ATTRIBUTE_BYTES FROM SPRING_SESSION S LEFT OUTER JOIN SPRING_SESSION_ATTRIBUTES SA ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID WHERE S.PRINCIPAL_NAME = ?"
      delete-sessions-by-expiry-time: "DELETE FROM SPRING_SESSION WHERE EXPIRY_TIME < ?"
  jackson:
    default-property-inclusion: "non-empty"
  ## H2 Console 설정
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        web-allow-others: true

## OPEN-API 설정
springdoc:
  packages-to-scan: "com.ntiple"
  default-consumes-media-type: "application/json; charset=UTF-8"
  default-produces-media-type: "application/json; charset=UTF-8"
  server:
    url: "/"
    description: "기본URL"
  swagger-ui:
    path: "/swagger/"
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: "/swagger/v3/api-docs/swagger-config"

logging:
  file:
    path: "log"
    filename: "was.log"
  level:
    root: INFO

## 기타 프로젝트 일반 설정
system:
  key-seed: "project-key-seed-2024-12-06"